# Generated by Django 3.1.7 on 2021-03-17 16:26

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField()),
                ('A', ckeditor.fields.RichTextField()),
                ('B', ckeditor.fields.RichTextField()),
                ('C', ckeditor.fields.RichTextField()),
                ('D', ckeditor.fields.RichTextField()),
                ('ANS', ckeditor.fields.RichTextField()),
                ('mark', models.PositiveSmallIntegerField(default=1)),
                ('negative_mark', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default=None, max_length=250)),
                ('total_mark', models.PositiveSmallIntegerField(default=0)),
                ('exam_time', models.DurationField(default=0)),
                ('exam_start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('subject_image', models.ImageField(upload_to='media/exam_subject/')),
                ('no_of_attempt', models.PositiveSmallIntegerField(default=1)),
                ('exam_created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjectsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.SmallIntegerField(default=0)),
                ('total_mark', models.SmallIntegerField(default=0)),
                ('submitted_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('exam_subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.examsubject')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswersheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=True)),
                ('user_ANS', ckeditor.fields.RichTextField()),
                ('mark', models.SmallIntegerField(default=0)),
                ('exam_question_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.examquestions')),
                ('exam_subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exam.examsubject')),
            ],
        ),
        migrations.AddField(
            model_name='examquestions',
            name='exam_subject_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ExamQuestions', to='exam.examsubject'),
        ),
    ]
