# Generated by Django 3.1.7 on 2021-03-22 17:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20210317_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestions',
            name='clickedSave',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='flag',
            field=models.SmallIntegerField(blank=True, default=2, null=True),
        ),
        migrations.AddField(
            model_name='examquestions',
            name='userSelectedAnswer',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
