# Generated by Django 3.1.7 on 2021-03-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20210322_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestions',
            name='A',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='ANS',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='B',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='C',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='examquestions',
            name='D',
            field=models.TextField(),
        ),
    ]
