# Generated by Django 3.1.7 on 2021-03-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210325_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswersheet',
            name='user_ANS',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
